// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7OM-ZWHY64RCaRppyTDxu4QEvijzyjU4',
    appId: '1:583459991082:web:b2b2a326499b706595dd53',
    messagingSenderId: '583459991082',
    projectId: 'gcwufhub',
    authDomain: 'gcwufhub.firebaseapp.com',
    storageBucket: 'gcwufhub.firebasestorage.app',
    measurementId: 'G-JKN5EEDCPF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqeGoCu888Da9wKk3pX3yc1OsD4-hkOI4',
    appId: '1:583459991082:android:a145e2b5575b5f0295dd53',
    messagingSenderId: '583459991082',
    projectId: 'gcwufhub',
    storageBucket: 'gcwufhub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJALl3FH8gzbePkGgGfO6Cb60nq_la5CE',
    appId: '1:583459991082:ios:5cf1bfd6cf9a2cca95dd53',
    messagingSenderId: '583459991082',
    projectId: 'gcwufhub',
    storageBucket: 'gcwufhub.firebasestorage.app',
    iosBundleId: 'com.example.gcwufHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJALl3FH8gzbePkGgGfO6Cb60nq_la5CE',
    appId: '1:583459991082:ios:5cf1bfd6cf9a2cca95dd53',
    messagingSenderId: '583459991082',
    projectId: 'gcwufhub',
    storageBucket: 'gcwufhub.firebasestorage.app',
    iosBundleId: 'com.example.gcwufHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7OM-ZWHY64RCaRppyTDxu4QEvijzyjU4',
    appId: '1:583459991082:web:6b4c902d056f9f5095dd53',
    messagingSenderId: '583459991082',
    projectId: 'gcwufhub',
    authDomain: 'gcwufhub.firebaseapp.com',
    storageBucket: 'gcwufhub.firebasestorage.app',
    measurementId: 'G-SFY5Y5BJ74',
  );
}
